### PR TITLE
Create postalregions

### PR DESCRIPTION
**Pull request by tomtaylor**
As part of creating [WOF's first postalregion places](https://github.com/whosonfirst-data/whosonfirst-data-admin-gb/pull/85), here's the spec update:

* I've made these `common_optional`
* I've added a [WikiData entry](https://www.wikidata.org/wiki/Q124695278) for them

### CODE REVIEW

**Comment by thisisaaronland** [comment]
Looks good to me.

Paging @nvkelso and @stepps00 for any additional comments.

**Comment by nvkelso** [comment]
LGTM, excited to see this land!

**Review by thisisaaronland — APPROVED** [review]

**Comment by tomtaylor** [comment]
Follow on PR https://github.com/whosonfirst/go-whosonfirst-placetypes/pull/5

**Comment by stepps00** [comment]
Thanks @tomtaylor, this looks great.

**Comment by missinglink** [comment]
Heya, I discovered today that this PR seems to have removed `constituency` from the spec JSON file?

https://github.com/whosonfirst/whosonfirst-placetypes/issues/34

**Pull request merged**
